# Generated by Django 4.0.4 on 2022-09-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('departmentId', models.AutoField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('employId', models.AutoField(primary_key=True, serialize=False)),
                ('employName', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=500)),
                ('doj', models.DateField()),
                ('photoName', models.CharField(max_length=500)),
            ],
        ),
    ]
